### PR TITLE
Feat: Add fbtftp to packages

### PR DESCRIPTION
**Pull request by oxedions**
Fbtftp contains official fbtftp files
Fbtftp_server contains server file and service file

### CODE REVIEW

**Review by btravouillon — COMMENTED** [review]
I would rather prefer to build a single RPM with the server embedded.
If you should keep 2 RPMS, can you add a requirement in the spec file? The server imports some fbtftp modules that are shipped within fbtftp RPM.

**Comment by oxedions** [comment]
I cab merge in a single rpm. However, since the spec file for python libs is auto-generated on the fly, I will need to insert the required files inside it. Also, it means that if I wish to update the server part, I will no more comply with original libs versions since I will need to increment version on my side.

This is why I preferred to keep 2 rpms, to be able to version and update freely the server side, while keeping versions sync with the fbtftp gitlab for the libs.

**Comment by oxedions** [comment]
Added the requires in the spec and solved conflicts.

**Review by bouriquet — APPROVED** [review]

**Review by btravouillon — APPROVED** [review]
Looks good to me. 👍

**Pull request merged**
